# Generated by Django 6.0.4 on 2026-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='Nivel_seguridad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
